name: Daily Download Count

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at midnight Pacific Time
  workflow_dispatch: # Allows manual triggering

jobs:
  update-download-counts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.25'

      - name: Setup git worktree for data branch
        run: git worktree add -b data data-worktree origin/data

      - name: Run download counter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd data-worktree
          go run ../cmd/github/main.go

      - name: Run Homebrew analytics collector
        run: |
          cd data-worktree
          go run ../cmd/brew/main.go

      - name: Run Chocolatey analytics collector
        run: |
          cd data-worktree
          go run ../cmd/chocolatey/main.go

      - name: Show Stats
        run: cat data-worktree/daily_stats.txt

      - name: Configure git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Commit and push changes
        run: |
          cd data-worktree
          git status --untracked-files=all
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          COMMIT_MSG=$(cat daily_stats.txt)
          git commit -m "chore: Update download counts" -m "$COMMIT_MSG"
          git push
